### ISSUE TITLE
关于公众号的收录规则

### ISSUE THREAD

**Issue by namasikanam** [thuservices/thuservices#28]
目前对于公众号的收录似乎还没有比较明确的规则：哪些公众号应收录于此，哪些公众号不应收录于此。

或许有一个较为明确的规则说明为好。

个人建议在大的原则上或许至少可以遵循：
1. 由清华学生、教师及教职工所建立；
2. 其内容以清华学生、教师或教职工为主体受众。
3. 最近几年内有推送发布。

当然，细想之下这里尚有诸多问题，比如说，清华校友是否应像在校学生一样被纳入考量呢？收录校友会之类的公众号是否合适呢？收录已毕业同学的个人公众号是否合适呢？收录已毕业的班级公众号——它们几乎都已“死”，不会再更新——是否合适呢？

**Comment by ZenithalHourlyRate** [comment]
LGTM. Please PR!

**Comment by namasikanam** [comment]
啊这，我这只是建议hhhh

以及校友的问题您怎么看？

**Comment by ZenithalHourlyRate** [comment]
> 以及校友的问题您怎么看？

单独列出来，类似「校友公众号」就行了
