### ISSUE TITLE
写了一个有关在 Windows 上自动登录校园网的指南

### ISSUE THREAD

**Issue by 84634E1A607A** [thuservices/thuservices#57]
或许可以放在 https://thu.services/services/#_5 里面?

https://aajax.top/2024/03/10/GoAuthingWindows/

**Comment by jiegec** [comment]
pr is welcome

**Comment by 84634E1A607A** [comment]
无法 Clone 此 Repo, 因为有一个文件夹叫 aux, 遭到了 Windows 的拒绝

**Comment by r-value** [comment]
> 无法 Clone 此 Repo, 因为有一个文件夹叫 aux, 遭到了 Windows 的拒绝

#49

**Comment by jiegec** [comment]
Please proceed.
