### ISSUE TITLE
在紫荆宿舍区的 Tsinghua Secure 观测到了 101.5.0.0/16 地址

### ISSUE THREAD

**Issue by 84634E1A607A** [thuservices/thuservices#59]
如图，在2024年4月宿舍区校园网断网维护后，部分 101.5.0.0/16 地址被分配给了宿舍区的无线网

![image](https://github.com/thuservices/thuservices/assets/60734649/e24ce5fd-d39c-4492-8606-a7246ee7b980)

**Comment by jiegec** [comment]
欢迎pr
